"""add savings attribution fields

Revision ID: 23f4437d1308
Revises: 4ca4a0281e99
Create Date: 2026-09-20 12:26:42.068453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23f4437d1308'
down_revision: Union[str, Sequence[str], None] = '4ca4a0281e99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_requests', sa.Column('requested_model', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_requests', 'requested_model')
    # ### end Alembic commands ###
