"""create llm requests table

Revision ID: 4ca4a0281e99
Revises: 
Create Date: 2026-09-19 23:15:10.985045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ca4a0281e99'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
    "llm_requests",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
    sa.Column("provider", sa.String(length=50), nullable=False),
    sa.Column("model_name", sa.String(length=100), nullable=False),
    sa.Column("prompt", sa.Text(), nullable=False),
    sa.Column("response", sa.Text(), nullable=False),
    sa.Column("input_tokens", sa.Integer(), nullable=False),
    sa.Column("output_tokens", sa.Integer(), nullable=False),
    sa.Column("total_tokens", sa.Integer(), nullable=False),
    sa.Column("estimated_cost", sa.Float(), nullable=False),
    sa.Column("actual_cost", sa.Float(), nullable=False),
    sa.Column("latency_ms", sa.Integer(), nullable=False),
    sa.Column("cache_hit", sa.Boolean(), nullable=False),
    sa.Column("routed", sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint("id"),
)
    op.create_index(op.f('ix_llm_requests_id'), 'llm_requests', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_requests_id'), table_name='llm_requests')
    op.drop_table('llm_requests')
    # ### end Alembic commands ###
