"""add savings metrics

Revision ID: 8d73b8f7f54d
Revises: 23f4437d1308
Create Date: 2026-09-20 16:17:42.496361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d73b8f7f54d'
down_revision: Union[str, Sequence[str], None] = '23f4437d1308'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


'''def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_requests', sa.Column('baseline_cost', sa.Float(), nullable=False))
    op.add_column('llm_requests', sa.Column('savings', sa.Float(), nullable=False))
    op.add_column('llm_requests', sa.Column('savings_percentage', sa.Float(), nullable=False))
    # ### end Alembic commands ###
'''

def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        'llm_requests',
        sa.Column(
            'baseline_cost',
            sa.Float(),
            server_default='0',
            nullable=False,
        ),
    )
    op.add_column(
        'llm_requests',
        sa.Column(
            'savings',
            sa.Float(),
            server_default='0',
            nullable=False,
        ),
    )
    op.add_column(
        'llm_requests',
        sa.Column(
            'savings_percentage',
            sa.Float(),
            server_default='0',
            nullable=False,
        ),
    )

    op.alter_column(
        'llm_requests',
        'baseline_cost',
        server_default=None,
    )
    op.alter_column(
        'llm_requests',
        'savings',
        server_default=None,
    )
    op.alter_column(
        'llm_requests',
        'savings_percentage',
        server_default=None,
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_requests', 'savings_percentage')
    op.drop_column('llm_requests', 'savings')
    op.drop_column('llm_requests', 'baseline_cost')
    # ### end Alembic commands ###