"""create semantic cache entries

Revision ID: be18aedb5a5b
Revises: 8d73b8f7f54d
Create Date: 2026-09-21 21:23:02.871957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be18aedb5a5b'
down_revision: Union[str, Sequence[str], None] = '8d73b8f7f54d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('semantic_cache_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('semantic_text', sa.Text(), nullable=False),
    sa.Column('embedding', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('finish_reason', sa.String(length=50), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('similarity_threshold', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_hit_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semantic_cache_entries_cache_key'), 'semantic_cache_entries', ['cache_key'], unique=True)
    op.create_index(op.f('ix_semantic_cache_entries_id'), 'semantic_cache_entries', ['id'], unique=False)
    op.create_index(op.f('ix_semantic_cache_entries_model'), 'semantic_cache_entries', ['model'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_semantic_cache_entries_model'), table_name='semantic_cache_entries')
    op.drop_index(op.f('ix_semantic_cache_entries_id'), table_name='semantic_cache_entries')
    op.drop_index(op.f('ix_semantic_cache_entries_cache_key'), table_name='semantic_cache_entries')
    op.drop_table('semantic_cache_entries')
    # ### end Alembic commands ###
